### ISSUE TITLE
swidval fails to run (commit 33cffbb4)

### ISSUE THREAD

**Issue by ajnelson-nist** [usnistgov/swid-tools#11]
# Describe the bug

Running `swidval-0.6.2-SNAPSHOT.jar` raises a class-not-found error immediately.

# Who is the bug affecting?

All `swidval` jar-file runners.

# What is affected by this bug?

`swival`.

# When does this occur?

Runtime.

# How do we replicate the issue?

1. Clone repository, state `33cffbb4`.
1. `cd` to repository root.
1. Build `swidval-0.6.2-SNAPSHOT.jar` by running `mvn clean install`.
1. Run `swidval/target/swidval-0.6.2-SNAPSHOT.jar` with or without arguments.

Bash transcript of last step:

```bash
$ java -jar .../swid-tools/swidval/target/swidval-0.6.2-SNAPSHOT.jar -h
Error: Unable to initialize main class gov.nist.secauto.swid.swidval.Application
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/cli/ParseException
```

# Expected behavior (i.e. solution)

`swidval` should run.

# Other Comments

I'm not sure if this is a classpath error.  It would be helpful if a Bash runner could be generated as a build artifact, a `swidval.sh` akin to `swidval/target/swidval-0.6.2-SNAPSHOT-swidval/swidval.bat`.

**Comment by david-waltermire-nist** [comment]
@ajnelson-nist Try the latest build. There should be a swidval script in the `bin` folder. I also fixed the classpath in the JAR manifest that was causing the above.

**Comment by ajnelson-nist** [comment]
This now runs and generates a report.  However, there is a behavior that I think is a regression.  I'll file another Issue.
