### ISSUE TITLE
swidval creates typo'd directory "schematon-results"

### ISSUE THREAD

**Issue by ajnelson-nist** [usnistgov/swid-tools#3]
Running swidval 0.5.0 creates a directory named `schematon-results`.  I suspect this is meant to be called `schematron-results` (adding an `r`).

**Comment by david-waltermire-nist** [comment]
I think this was fixed before the code was migrated to this repo. I will verify and close this once verified..

**Comment by ajnelson-nist** [comment]
Thanks!
